### ISSUE TITLE
Format doesn't appear for Rayman 2

### ISSUE THREAD

**Issue by rtsonneveld** [zeroKilo/N64LoaderWV#1]
Hi, when trying to load Rayman 2 N64 (.z64 file), I do not see the N64 Loader Format appear, only the raw binary format option. I have restarted Ghidra after ticking the install checkbox. Any idea how to fix this?

I use the latest stable Ghidra version (9.0.4)

**Comment by zeroKilo** [comment]
can you please tell me the first 4 bytes of your rom image? or where you got that rom from?

**Comment by rtsonneveld** [comment]
Sure, 80 37 12 40

It's just your regular old Rayman 2 NTSC ROM.

**Comment by zeroKilo** [comment]
hmm, well I can load it fine, no idea what the problem could be. you could try to compile it yourself, (I used this as a start https://habr.com/en/post/443318/) you could redownload the entire thing (made an update yesterday) or come to discord and chat with me. I really dunno, btw, I send you a screenshot on your yt comment that I really can load it. greetz

**Comment by rtsonneveld** [comment]
Sure, just add me on Discord (Robin#8003)

**Comment by rtsonneveld** [comment]
Issue has been fixed by installing OpenJDK 12 and using that. Thanks a lot! ^^
