### ISSUE TITLE
Importing Debug/Symbol Data

### ISSUE THREAD

**Issue by WNKLER** [zeroKilo/N64LoaderWV#16]
If I compiled a rom from source, how can I import debug/symbol information into Ghidra to help with analysis?

I'm trying to get a better idea of how specific code works at the hardware level once compiled.

**Comment by zeroKilo** [comment]
well sofar the plugin only supports symbol finding by pattern, see "signatures.txt" as example. (aka it looks for bytepattern) if you compile it yourself, I would first need to see in what format the debug symbols are stored, if its pdb, ghidra can maybe load the sybols itself already, if not, some loading function has to be written

**Comment by zeroKilo** [comment]
closed due to inactivity
