### ISSUE TITLE
[enhancement] building on linux is not straightforward, I suggest adding instructions to the readme.

### ISSUE THREAD

**Issue by TheBeardOfTruth** [zeroKilo/N64LoaderWV#17]
On arch linux (and any system in which you've installed ghidra with your distro's package manager, likely most of them) it's not obvious what GHIDRA_INSTALL_DIR should be.

This one-liner should provide the correct directory, so long ghidra is in PATH:

`GHIDRA_INSTALL_DIR=$(dirname $(readlink -fe $(which ghidra))) gradle`

we run `which ghidra`, then we figure out what that path is a symlink to using `readlink -fe`, and then we use the return value of that as the environment value, we then run gradle with this env preloaded (we may not want to export it as this could clobber the user's environment).

**Comment by zeroKilo** [comment]
if you could make a proper setup text for linux users,that I can c&p into the readme, then I can credit you, if you like :) I dont have ghidra on linux installed, I mainly use windows

**Comment by TheBeardOfTruth** [comment]
It'll be arch-linux centric but a typical linux user will know what changes they need to make to suit their distro (assuming their distro has ghidra in repos, if it doesn't then they'll trivially know where ghidra's installed to since they did it manually)

Here's a quick set of instructions, feel free to re-word it if necessary.

> install java11, gradle, and ghidra, on arch linux (substitute as needed for apt, yum, or what have you):
> 
> `pacman -S jdk11-openjdk gradle ghidra`
> 
> I'm using openjdk 11, but pretty much any flavour of java 11+ should work.
>
> Clone the repo and cd to the N64LoaderWV directory
> `git clone https://github.com/zeroKilo/N64LoaderWV.git`
>
> if ghidra is in your PATH (you may need to use ghidraRun instead of ghidra depending on distro):
> `GHIDRA_INSTALL_DIR=$(dirname $(readlink -fe $(which ghidra))) gradle`
>
> else set `GHIDRA_INSTALL_DIR` to where you manually installed ghidra to (e.g `$HOME/bin`) or add ghidra's location to PATH

**Comment by zeroKilo** [comment]
ok, done, and thanks for your input :) btw, this project is build on jdk 13 if that matters, iirc there were some problems when using older jdks

**Comment by TheBeardOfTruth** [comment]
it appears to build and run fine on jdk11 on my end, aside from ghidra complaining about some missing instructions occasionally. That's probably just me picking a bad cpu (BE:64:32, tried a few variants)

But yeah, the instructions can specify any version (they follow a predictable pattern)

java 15 should be good, no? That's available via jdk-openjdk

various other versions like `jdk13-openj9-bin` are also available, though without knowing what problem java 11 is supposed to pose I can't comment. (it also might differ with OpenJDK11 and other implementations)

EDIT: put the JDK version of the package instead of JRE, since building is required.

**Comment by zeroKilo** [comment]
you lost me there... can you just put the correct code line for jdk 13 so I can replace it?

`pacman -S jdk13-openjdk gradle ghidra`

is this wrong or what?

**Comment by TheBeardOfTruth** [comment]
jdk 13 isn't in repos, it would need to be build from the user repository. jdk11-openjdk and jdk-openjdk (current version, 15 in this case) are what's available easily.

jdk13-openj9-bin is in the AUR.

**Comment by zeroKilo** [comment]
so
`pacman -S jdk13-openj9-bin gradle ghidra`

would be correct? see, im not a linux user that much so no idea how java works there, all I know is, that I use jdk13 to build these, so having instructions for jdk11 dont seem useful

**Comment by TheBeardOfTruth** [comment]
Sadly not. that package has to be built manually (the AUR is user-submitted packages so they can only be installed manually for security reasons)

jdk11 works on my end, I'm not sure what error you get with it.
jdk15 should work too, no? Can just skip the first line of the instructions and let the user figure out what dependencies they need as well.

> Dependencies: gradle, ghidra, java (jdk13 recommended)

**Comment by zeroKilo** [comment]
so

`pacman -S jdk15-openjdk gradle ghidra`

yes?

**Comment by TheBeardOfTruth** [comment]
That works, yes. (I had to double check, it's also aliased as jdk-openjdk since it's the current version, but it does work)

**Comment by zeroKilo** [comment]
alright, will update, thx for the input
