### ISSUE TITLE
Update for V10.x, reinstate .ddreg's And add more accurate CPU config

### ISSUE THREAD

**Issue by blackgamma7** [zeroKilo/N64LoaderWV#18]
This extension should be updated for Ghidra 10.x, And I saw the N64 DD registers were absent in this build - they can be found in an older commit. Also, there is a slightly more accurate version of the N64's CPU, noted here: https://github.com/mkst/conker/wiki/Using-Ghidra

**Comment by zeroKilo** [comment]
you seem to use my plugins alot, would you like to contact me on reddit so we can chat? seems this wont be the last update to this plugin :)
Im trying to make a new build now, please check if its ok, thank you
