### ISSUE TITLE
Currently not working on Ghidra 10.1.5 (Ubuntu)

### ISSUE THREAD

**Issue by Xoffio** [zeroKilo/N64LoaderWV#21]
![Screenshot from 2022-10-06 01-37-22](https://user-images.githubusercontent.com/38369407/194222816-8bf7c666-8715-456c-81f2-cd589a9f4f7b.png)
i made sure to download the latest version and the latest release but this happens

**Comment by zeroKilo** [comment]
from your screenshot its visible that you inserted the version 10.1.4 not 10.1.5. I just downloaded the latest release by hand and checked the "extension.properties" inside the zip, it says "version=10.1.5" so im not sure what you did there. Maybe try to redownload and check that file first, if you still have problems, let me know and I investigate deeper :)

**Comment by Xoffio** [comment]
hi @zeroKilo. I just followed this commands and no luck

```bash
$ cd /home/xoffio/Downloads/ghidra_10.1.5_PUBLIC_20220726/ghidra_10.1.5_PUBLIC/Extensions/Ghidra
$ wget https://github.com/zeroKilo/N64LoaderWV/archive/refs/tags/10.1.5.tar.gz
$ tar -xvf 10.1.5.tar.gz
$ cp N64LoaderWV-10.1.5/dist/N64LoaderWV.zip ghidra_10.1.5_PUBLIC_20220726_N64LoaderWV
$ rm -rf 10.1.5.tar.gz
$ rm -rf N64LoaderWV-10.1.5
$ ../../ghidraRun
```
I downloaded Ghidra 10.1.4 to make it work but you should look into.... 

let me know if i can help you in anything or if i did something wrong.

**Comment by zeroKilo** [comment]
![image](https://user-images.githubusercontent.com/12677118/194553870-c1874056-1b82-4337-94c7-6483a5f6eda7.png)
pls try to put the file there by hand, download it with a browser I guess, I can only test this on windows and it works fine for me

EDIT: this would be current download url I guess: https://github.com/zeroKilo/N64LoaderWV/files/9339297/N64LoaderWV.zip

**Comment by Xoffio** [comment]
that link does work! I think the zip in the dist folder is outdated. Thanks I think we can close this issue
