### ISSUE TITLE
Extension can not be loaded

### ISSUE THREAD

**Issue by Justman10000** [zeroKilo/N64LoaderWV#22]
Hi, i installed N64Loader in <Ghydra_Path>\Extensions\Ghidra, only then comes this:

![grafik](https://user-images.githubusercontent.com/49990629/196978126-88240bee-c6c6-4859-a4e9-018a7c4dbe1b.png)

It is marked in red and cannot be selected either!

**Comment by zeroKilo** [comment]
you need to either use the release from the side of the github page or recompile it with your ghidra version, as you see, you inserted the extension for 10.1.4 not 10.1.5

**Comment by Justman10000** [comment]
> you need to either use the release from the side of the github page or recompile it with your ghidra version, as you see, you inserted the extension for 10.1.4 not 10.1.5
> 
> EDIT: insert zip from here: https://github.com/zeroKilo/N64LoaderWV/releases/tag/10.1.5

I had downloaded the .zip from the master branch

**Comment by zeroKilo** [comment]
thats the source, for when you want to recompile it, so it works now? can this ticket be close?

**Comment by Justman10000** [comment]
And where are the source codes of the N64 game? I only see the bytes

![grafik](https://user-images.githubusercontent.com/49990629/196983768-92ba4998-32b5-448e-a48c-da99db9059e1.png)

**Comment by Justman10000** [comment]
Yes, it works!

**Comment by Justman10000** [comment]
And where are the source codes of the N64 game? I only see the bytes

![grafik](https://user-images.githubusercontent.com/49990629/196983768-92ba4998-32b5-448e-a48c-da99db9059e1.png)

**Comment by zeroKilo** [comment]
this is not a place for tutorials, please watch some yt tutorials first, thanks. (code would be on the right, where it says decompiler, but your cursor is not in a code location)

**Comment by Justman10000** [comment]
> this is not a place for tutorials, please watch some yt tutorials first, thanks. (code would be on the right, where it says decompiler, but your cursor is not in a code location)
> 
> EDIT: example from my channel https://www.youtube.com/watch?v=3d3a39LuCwc

Is it normal that the decompiled code looks so strange?

![grafik](https://user-images.githubusercontent.com/49990629/197000424-97e79c87-a5cc-4f2b-8611-2f7c0686e0f3.png)

**Comment by Justman10000** [comment]
Where is the correct source code?

**Comment by Justman10000** [comment]
> you might wanna google what decompiling means, you dont get source code, you get pseudo-code that would compile to the same asm, but there are no variable names or function names stored in a rom
> 
> EDIT: in any case, I think your initial issue is solved, please close this then
> 
> EDIT2: a paper I wrote about a control flow decompiler for example: https://github.com/zeroKilo/DirectedGraphsWV/blob/master/How%20to%20write%20a%20basic%20control%20flow%20decompiler.pdf this is intended for people that want to write one, but in your case you might see how much work is involved. if you need a general crash course in reverse engineering I made this too: https://www.reddit.com/r/REGames/comments/f781mh/re_with_wv_hi_i_made_a_series_of_10_episodes/

Would it be possible to get the original source code?

**Comment by zeroKilo** [comment]
can you read the FIRST FUCKING sentence of the very text you just quoted?!?!?

>  you dont get source code

you DO NOT get ORIGINAL source code, its PSEUDO source code!!! and im not going to explain you decompiling, I already pointed you to materials, just read them or use google! 

this here is for bug reports, not chatting or teaching! so unless you have a bug to report, leave this closed!
