### ISSUE TITLE
How to create Signatures?

### ISSUE THREAD

**Issue by RetroGameDeveloper** [zeroKilo/N64LoaderWV#4]
First of all great plugin, it works like a charm! But I am not sure how to create signatures for the loader, is it possible to use IDA/Yara files from here:
https://assemblergames.com/threads/reverse-engineering-n64-signature-files-for-ida-pro-radare2.70138/

Many thanks

**Comment by zeroKilo** [comment]
check https://github.com/zeroKilo/N64LoaderWV/blob/master/signatures.txt for an example, its just name,space,hexpattern, where ?? = byte to ignore
greetz

**Comment by zeroKilo** [comment]
if you have no further questions, im gonna close this issue
