### ISSUE TITLE
freez 411k

### ISSUE THREAD

**Issue by Rus3545** [zeroKilo/N64LoaderWV#6]
This freezes for OoTMQ (Debug Version) Auto Analyzis.

**Comment by zeroKilo** [comment]
please open an issue at the ghidra repo, I dont think its related to my code, unless you can show me what to change in my code

**Comment by zeroKilo** [comment]
so I tried to replicate this error and you are right, it does indeed run out of memory, but if you skip the analyzing part, its loaded correctly and you can always go ahead and find/decompile functions per hand. the loader did its part, so this is a problem of ghidra itself and im going to close this ticket now. please open an issue at the github there
