### ISSUE TITLE
can't get the plugin to recognize N64 files

### ISSUE THREAD

**Issue by ElectronAsh** [zeroKilo/N64LoaderWV#8]
Hi,

Thanks for writing this plugin. I'm sure it works great, but I'm having major trouble getting it to recognize N64 ROM files.

I've tried using the latest Ghidra 9.1-BETA_Dev from the official site.

I can get the extension to seemingly install fine, by copying the N64LoaderWV.zip file into C:\ghidra_9.1-BETA_DEV\Extensions\Ghidra, then renaming the start of the file to match the sig of the sample.

That then apparently extracts the extension zip into C:\ghidra_9.1-BETA_DEV\Ghidra\Extensions

(which is quite confusing, btw, but that's a Ghidra folder naming convention.)

I have Mario 64 as SM64.n64 and SM64.z64 in C:\ghidra_projects

The .n64 file is byte-swapped, so says "RAMIO 46" etc. in the cart header. The .z64 is normal endianess, so says "MARIO 64".

But Ghidra still only detects the ROM file(s) as raw binary?

So I then tried downloading the older 9.0.4 commit of your extension, and the older 9.0.4 of Ghidra, deleted the old project, installed the extension, restarted Ghidra, created a new project, and tried doing an Import of SM64 again, but no joy. It's like the extension isn't being run at all?

I'm on Win 10 x64 on an i5. I tried running ghidraRun.bat as Administrator, but nothing seems to help.

![image](https://user-images.githubusercontent.com/24658385/70004352-e23cd200-155d-11ea-8397-33ca04390bdd.png)

![image](https://user-images.githubusercontent.com/24658385/70004617-d69ddb00-155e-11ea-8a97-dd5df0904896.png)

![image](https://user-images.githubusercontent.com/24658385/70004627-e1587000-155e-11ea-8bc4-f609788c3232.png)

**Comment by ElectronAsh** [comment]
Ahh, I only just spotted the reply from somebody on your YT vid, saying that JDK 12 or higher may be needed to allow the extension to run properly.

I'll try that now.

I also just joined the Discord, so easier to ask in there. ;)

**Comment by zeroKilo** [comment]
ehm ok, so can this be closed?

**Comment by ElectronAsh** [comment]
I still couldn't get it working after installing JDK 13 then restarting.

I'll discuss on Discord instead, so yep, I'll close the issue. Thanks.
